version: '3.7'
services:
  vault_transit:
    image: vault:my-tag
    ports:
      - "8202:8200"
    expose:
      - "8201"
    environment:
      - VAULT_UI=true
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_LICENSE=${VAULT_LICENSE}
      - SKIP_SETCAP=true
    volumes:
      - ./vault_transit.hcl:/vault/config/vault_transit.hcl
  vault_1:
    image: vault:my-tag
    command: server
    ports:
      - "8200:8200"
    expose:
      - "8201"
    environment:
      - VAULT_LOCAL_CONFIG={"api_addr":"http://vault_1:8200","cluster_addr":"http://vault_1:8201"}
      - VAULT_UI=true
      - VAULT_LICENSE=${VAULT_LICENSE}
      - SKIP_SETCAP=true
    volumes:
      - ${PWD}/vault-auth-plugin-example/vault-auth-plugin-example:/usr/local/bin/vault/vault-auth-plugin-example
      - ${PWD}/vault_primary.hcl:/vault/config/vault_primary.hcl
    depends_on:
      - consul
      - vault_transit
  consul:
    image: consul:1.6.3
    environment:
      - CONSUL_LOCAL_CONFIG={"log_level":"INFO"}
  vault2_1:
    image: vault:my-tag
    command: server
    ports:
      - "8300:8200"
    expose:
      - "8201"
    environment:
      - VAULT_LOCAL_CONFIG={"api_addr":"http://vault2_1:8200","cluster_addr":"http://vault2_1:8201"}
      - VAULT_UI=true
      - VAULT_LICENSE=${VAULT_LICENSE}
      - SKIP_SETCAP=true
    volumes:
      - ${PWD}/vault-auth-plugin-example/vault-auth-plugin-example:/usr/local/bin/vault/vault-auth-plugin-example
      - ${PWD}/vault_pr.hcl:/vault/config/vault_pr.hcl
    depends_on:
      - consul2
      - vault_transit
  consul2:
    image: consul:1.6.3
    environment:
      - CONSUL_LOCAL_CONFIG={"log_level":"INFO"}
  statsd:
    image: graphiteapp/graphite-statsd:1.1.7-6
    ports:
      - "8125:8125/tcp"
      - "8125:8125/udp"
      - "80:80"
      - "2003:2003"
      - "2004:2004"
      - "2023:2023"
      - "2024:2024"
