FROM golang:1.16.4-alpine3.13

RUN apk add --no-cache git

# Setup up tooling
RUN git clone https://github.com/hashicorp/vault-auth-plugin-example.git /go/src/github.com/hashicorp/vault-auth-plugin-example && \
    mkdir -p /tmp/.cache && \
  rm -rf /tmp/*

# Build the spiffe helper
ENV GO111MODULE=on
ENV GOCACHE=/tmp/.cache
WORKDIR /go/src/github.com/hashicorp/vault-auth-plugin-example
RUN go build -v .
WORKDIR /

# Now build the final container with Vault and Spiffe-Helper
FROM hashicorp/vault-enterprise:1.5.7_ent
RUN mkdir -p /usr/local/bin/vault
COPY --from=0 /go/src/github.com/hashicorp/vault-auth-plugin-example/vault-auth-plugin-example /usr/local/bin/vault/vault-auth-plugin-example
RUN chmod +x /usr/local/bin/vault/vault-auth-plugin-example && setcap cap_ipc_lock=+ep /usr/local/bin/vault/vault-auth-plugin-example
RUN sha256sum /usr/local/bin/vault/vault-auth-plugin-example >> /usr/local/bin/vault/vault-auth-plugin-example-sha256sum
RUN cat /usr/local/bin/vault/vault-auth-plugin-example-sha256sum
